export interface KnowledgeEntry {
  id: string;
  category: string;
  subcategory: string;
  title: string;
  content: string;
  keywords: string[];
  lastUpdated: string;
  source: string;
}

export const KNOWLEDGE_BASE: KnowledgeEntry[] = [
  {
    id: "kvp-2024",
    category: "post-office",
    subcategory: "investment",
    title: "Kisan Vikas Patra (KVP)",
    content: `KVP is a post office savings scheme. Reference rate often quoted around 7.5% p.a. (verify current rate on India Post / RBI notifications — rates reset quarterly). Typical past pattern: money doubles over a tenure set by the government (previously ~115 months; confirm at purchase). Minimum investment: ₹1,000. No statutory maximum. Available at post offices and authorised banks. Premature withdrawal: typically after 2.5 years (scheme rules). Tax: interest is taxable as income. TDS may apply if interest exceeds thresholds (e.g. ₹40,000/year for non-seniors — verify current limits). Best for: parking lump sums for a guaranteed, government-backed return; building an insurance-premium ladder.`,
    keywords: ["kvp", "kisan vikas patra", "post office", "double money", "guaranteed return", "fd strategy"],
    lastUpdated: "2024-04-01",
    source: "India Post",
  },
  {
    id: "ssy-2024",
    category: "post-office",
    subcategory: "girl-child",
    title: "Sukanya Samriddhi Yojana (SSY)",
    content: `SSY is a government scheme for girl child savings. Rate is notified by the government (often cited around 8.2% p.a. in 2024 — always confirm the live rate at opening). Maximum investment: ₹1,50,000 per financial year. Minimum: ₹250 per year. Account opens from birth until the girl turns 10 — cannot open after age 10. Maturity when the girl turns 21; partial withdrawal possible for education around 18 per rules. Tax: EEE in eligible cases (subject to IT law). Best for: girl child education and marriage corpus. Illustrative only: monthly discipline over many years compounds — model with current rate and limits.`,
    keywords: ["ssy", "sukanya", "girl child", "daughter", "post office girl scheme"],
    lastUpdated: "2024-04-01",
    source: "India Post / Finance Ministry",
  },
  {
    id: "scss-2024",
    category: "post-office",
    subcategory: "senior-citizen",
    title: "Senior Citizen Savings Scheme (SCSS)",
    content: `SCSS is for senior citizens (typically 60+; special rules for those who took VRS). Rate is government-notified (often ~8.2% p.a. in recent cycles — verify at investment). Maximum: ₹30 lakh per eligible person. Tenure: 5 years, extendable by 3 years. Quarterly interest payout. Tax: interest taxable; TDS thresholds apply (e.g. ₹50,000 for seniors in many cases — verify). 80C may apply on principal in old regime subject to limits. Best for: retirement income stream from a lump sum.`,
    keywords: ["scss", "senior citizen", "retirement", "post office senior"],
    lastUpdated: "2024-04-01",
    source: "India Post",
  },
  {
    id: "rd-post-office",
    category: "post-office",
    subcategory: "recurring",
    title: "Post Office Recurring Deposit (RD)",
    content: `Post Office RD for monthly savings. Rate is notified quarterly (example ~6.7% p.a. in 2024 literature — confirm live rate). Minimum ₹100/month; no fixed maximum. Tenure often 5 years (60 months). Premature rules per India Post circular. Tax: interest taxable. Best for: monthly discipline — e.g. building next year’s insurance premium pot.`,
    keywords: ["rd", "recurring deposit", "post office rd", "monthly saving"],
    lastUpdated: "2024-04-01",
    source: "India Post",
  },
  {
    id: "mis-post-office",
    category: "post-office",
    subcategory: "monthly-income",
    title: "Post Office Monthly Income Scheme (MIS)",
    content: `MIS pays monthly interest on a lump sum. Rate notified by government (example ~7.4% p.a. in 2024 — verify). Caps apply on investment (e.g. ₹9 lakh single / ₹15 lakh joint historically — confirm current). Tenure often 5 years. Tax: interest taxable. Best for: retirees wanting regular payouts from capital.`,
    keywords: ["mis", "monthly income", "post office mis", "monthly payout", "passive income"],
    lastUpdated: "2024-04-01",
    source: "India Post",
  },
  {
    id: "term-insurance-rules",
    category: "insurance",
    subcategory: "term-life",
    title: "Term Insurance Rules for India",
    content: `Term insurance: rough cover heuristic = annual income × 10, plus major loans, plus buffers for dependants (modelling often adds ₹20–25L per dependent — adjust to reality). Premium rises sharply with age; buying earlier is cheaper. Illustrative ₹1 crore premiums (vary by insurer/health): ~₹700–900/mo at 25, ~₹900–1,200 at 30, ~₹1,400–1,800 at 35, ~₹2,200–2,800 at 40 — always quote after underwriting. Education loan co-signers (often parents) remain liable if the borrower dies — term cover naming the right nominees matters. Use IRDAI-published claim settlement ratios as one input (not the only one).`,
    keywords: ["term insurance", "life cover", "term plan", "claim settlement", "co-signer", "education loan"],
    lastUpdated: "2024-04-01",
    source: "IRDAI / industry practice",
  },
  {
    id: "health-insurance-rules",
    category: "insurance",
    subcategory: "health",
    title: "Health Insurance Rules India",
    content: `Cover heuristics (indicative): metro single ~₹10L; couple floater ~₹15L; family with children often ₹20–25L+; tier-2 cities often ~30% lower than metro; parents may need separate senior policies ₹5–10L+. Watch waiting periods (PED 2–4 years common), room-rent sub-limits, restore benefits, NCB. Employer cover ends with job — keep a personal floater. Maternity: often 24-month wait — buy before planning pregnancy.`,
    keywords: ["health insurance", "mediclaim", "health cover", "family floater", "maternity", "baby", "pregnancy"],
    lastUpdated: "2024-04-01",
    source: "IRDAI",
  },
  {
    id: "tax-80c",
    category: "tax",
    subcategory: "deductions",
    title: "Section 80C Tax Deductions",
    content: `80C deduction limit: ₹1,50,000/year (old regime). Includes ELSS (3y lock-in), PPF, EPF (employee), NSC, SSY, SCSS (eligible taxpayers), tax-saving FD (5y), life insurance premium (conditions), principal on home loan (conditions), tuition fees, etc. New tax regime: 80C generally not available — verify current IT rules. Young investors often use ELSS for growth + discipline; blend with PPF/debt as age rises.`,
    keywords: ["80c", "tax saving", "elss", "ppf", "tax deduction", "emergency fund"],
    lastUpdated: "2024-04-01",
    source: "Income Tax Act",
  },
  {
    id: "tax-80d",
    category: "tax",
    subcategory: "health-deduction",
    title: "Section 80D Health Insurance Deduction",
    content: `80D: premium for self/family up to ₹25,000 (₹50,000 if senior citizen). Additional for parents: ₹25,000 (or ₹50,000 if parents are 60+). Combined caps apply per IT rules. Preventive health check-up sub-limit (₹5,000 within overall limits historically — verify). Available in both regimes for health premium in many cases — confirm annually.`,
    keywords: ["80d", "health insurance deduction", "medical deduction"],
    lastUpdated: "2024-04-01",
    source: "Income Tax Act",
  },
  {
    id: "tax-80e",
    category: "tax",
    subcategory: "education-loan",
    title: "Section 80E Education Loan Interest",
    content: `80E: deduction for interest on education loan for higher education (specified lender/institution rules). Deduction for interest for up to 8 assessment years or until interest is paid, whichever is earlier — subject to conditions. Typically old-regime benefit — verify. Does not reduce principal obligation; still prioritise clearing high-cost debt vs taxable investing.`,
    keywords: ["80e", "education loan", "student loan", "interest deduction"],
    lastUpdated: "2024-04-01",
    source: "Income Tax Act",
  },
  {
    id: "nps-rules",
    category: "investment",
    subcategory: "retirement",
    title: "National Pension System (NPS)",
    content: `NPS: additional ₹50,000 deduction under 80CCD(1B) over 80C for eligible subscribers (verify). Market-linked returns; historical blended returns vary by choice (E/C/G). At exit, regulatory rules require annuitisation of a portion (e.g. 40% annuity, 60% lump sum at 60 in many cases — rules evolve). Premature exit is restrictive. Equity cap in auto choice depends on age. Useful for salaried wanting extra tax deferral and self-employed without EPF.`,
    keywords: ["nps", "national pension", "80ccd", "retirement corpus", "retirement"],
    lastUpdated: "2024-04-01",
    source: "PFRDA",
  },
  {
    id: "education-loan-rules",
    category: "debt",
    subcategory: "education",
    title: "Education Loan Strategy India",
    content: `Prioritise clearing education loan before aggressive risk investing if post-tax loan cost exceeds expected post-tax investment return. 80E may help interest (old regime, conditions). Co-signer risk: parents often liable — align term insurance. Accelerate with prepayments from bonuses; avoid adding consumer debt alongside.`,
    keywords: ["education loan", "student loan", "80e", "co-signer"],
    lastUpdated: "2024-04-01",
    source: "RBI / Income Tax",
  },
  {
    id: "emergency-fund-basics",
    category: "basics",
    subcategory: "liquidity",
    title: "Emergency fund (India context)",
    content: `Keep 3–12 months of non-discretionary expenses in liquid, low-volatility instruments (savings + liquid mutual funds). FDs are not fully liquid — assume haircut/penalty if breaking early. Credit cards are not the emergency fund; they are expensive if revolved. Ring-fence medical and premium buckets separately where possible.`,
    keywords: ["emergency fund", "liquidity", "liquid mf", "savings"],
    lastUpdated: "2024-04-01",
    source: "Finkoin methodology",
  },
  {
    id: "planning-baby",
    category: "life-events",
    subcategory: "family-planning",
    title: "Financial Planning for New Baby India",
    content: `Before pregnancy: add/check maternity cover (waiting periods common), build ~6 months joint expenses buffer, understand employer maternity (26 weeks paid maternity per law for eligible establishments) and paternity policies. Delivery costs vary widely (govt vs private metro). Budget first-year childcare, paediatric visits, essentials. Start small, goal-tagged investments early for education horizon.`,
    keywords: ["baby", "pregnancy", "maternity", "new born", "family planning baby", "planning baby"],
    lastUpdated: "2024-04-01",
    source: "Various",
  },
];
