import {
  newAnalyseRowId,
  normalizeAnalyseFormValues,
  type AnalyseFormValues,
} from "@/lib/analyse-form-schema";

/** User-provided analyse scenario (Aug 2026) for regression tests. */
export function buildUserAnalyseScenarioForm(): AnalyseFormValues {
  return {
    lifeStage: "married",
    selfAge: 35,
    spouseAge: 33,
    cityTier: "metro",
    monthlySalary: 275_000,
    spouseIncome: 140_000,
    otherIncome: 0,
    rentAmount: 36_750,
    rentMaintenanceMonthly: 0,
    unifiedLoans: [
      {
        id: newAnalyseRowId(),
        loanType: "personal_loan",
        lenderName: "BANK A",
        monthlyEMI: 66_172,
        outstandingAmount: 2_657_000,
        interestRate: 11,
        remainingMonths: 52,
      },
      {
        id: newAnalyseRowId(),
        loanType: "personal_loan",
        lenderName: "BANK B",
        monthlyEMI: 42_055,
        outstandingAmount: 1_650_000,
        interestRate: 11,
        remainingMonths: 52,
      },
    ],
    homeLoanEMI: 27_860,
    personalLoanEMI: 0,
    carLoanEMI: 0,
    bikeEMI: 0,
    secondPropertyEMI: 0,
    creditCardBillMonthly: 0,
    additionalObligations: [],
    foodTotal: 10_000,
    transportTotal: 25_000,
    utilityTotal: 4_000,
    domesticHelpTotal: 8_500,
    lifestyleTotal: 2_000,
    vegetables: 0,
    grocery: 0,
    medicine: 0,
    fuel: 0,
    cabMetro: 0,
    electricity: 0,
    internet: 0,
    gas: 0,
    water: 0,
    houseHelpMonthly: 0,
    cookHelpMonthly: 0,
    entertainment: 0,
    shopping: 0,
    personalCare: 0,
    parentsSupport: 0,
    hasHealthInsurance: true,
    healthInsuranceSumInsured: 6_000_000,
    healthInsurancePremiumInput: 19_853,
    healthInsurancePremiumFrequency: "yearly",
    hasTermInsurance: true,
    termInsuranceSumAssured: 10_000_000,
    termInsurancePremiumInput: 18_599,
    termInsurancePremiumFrequency: "yearly",
    termInsurancePremiumTillYear: 2053,
    carInsurancePremiumInput: 15_000,
    carInsurancePremiumFrequency: "yearly",
    bikeInsurancePremiumInput: 1_000,
    bikeInsurancePremiumFrequency: "yearly",
    hasOtherInsurance: true,
    otherInsurancePremiums: [
      {
        id: newAnalyseRowId(),
        policyName: "LIC monthly",
        premiumAmount: 2_895,
        frequency: "monthly",
        maturityAmount: 1_800_000,
        maturityYear: 2042,
      },
      {
        id: newAnalyseRowId(),
        policyName: "LIC yearly",
        premiumAmount: 67_386,
        frequency: "yearly",
        maturityAmount: 3_800_000,
        maturityYear: 2045,
      },
    ],
    fdValue: 500_000,
    fdRate: 8,
    fdMaturityYear: 2027,
    fdTenureYears: 1,
    emergencyFundCurrent: 700_000,
    epfBalance: 1_200_000,
    totalEquityValue: 1_500_000,
    goldValue: 1_000_000,
    customInvestments: [
      {
        label: "Equity RSU",
        currentValue: 1_900_000,
        monthlyContribution: 0,
        type: "equity",
      },
    ],
    ownsHome: true,
    homeMarketValue: 6_000_000,
    homeLoanOutstanding: 2_950_000,
    ownsCar: true,
    carMarketValue: 800_000,
    monthlyEPFContribution: 19_000,
    hasPostOfficeSchemes: true,
    postOfficeSchemes: [
      {
        id: newAnalyseRowId(),
        scheme: "nsc",
        amount: 150_000,
        maturityYear: 2027,
      },
    ],
    primaryGoal: "retire_early",
    retirementTargetCorpus: 30_000_000,
    retirementAge: 42,
    monthlySIP: 0,
    savingsAccountBalance: 0,
    liquidMFValue: 0,
    otherLiquidSavings: 0,
    mfValue: 0,
    indianStocksValue: 0,
    usStocksValueINR: 0,
    usMFValueINR: 0,
    rsuValueINR: 0,
    ppfBalance: 0,
    npsBalance: 0,
    investsInNsc: true,
    nscDepositAmount: 150_000,
    nscMaturityYear: 2027,
  } as AnalyseFormValues;
}

export function buildUserAnalyseScenarioProfile() {
  return normalizeAnalyseFormValues(buildUserAnalyseScenarioForm());
}
