export const TRACKER_CATEGORIES = {
  needs: {
    label: "Needs",
    color: "#534AB7",
    emoji: "🏠",
    cap: 30,
    subcategories: [
      { id: "rent", label: "Rent / Home loan EMI", emoji: "🏠" },
      { id: "groceries", label: "Groceries", emoji: "🛒" },
      { id: "vegetables", label: "Vegetables & fruits", emoji: "🥦" },
      { id: "milk", label: "Milk & dairy", emoji: "🥛" },
      { id: "electricity", label: "Electricity bill", emoji: "⚡" },
      { id: "water", label: "Water bill", emoji: "💧" },
      { id: "gas", label: "Gas / LPG", emoji: "🔥" },
      { id: "internet", label: "Internet / broadband", emoji: "🌐" },
      { id: "mobile", label: "Mobile recharge", emoji: "📱" },
      { id: "school_fees", label: "School / college fees", emoji: "🎓" },
      { id: "medicine", label: "Medicine", emoji: "💊" },
      { id: "doctor", label: "Doctor / hospital", emoji: "🏥" },
      { id: "domestic_help", label: "Maid / cook / driver", emoji: "🧹" },
      { id: "transport_essential", label: "Transport to work", emoji: "🚌" },
    ],
  },
  wants: {
    label: "Wants",
    color: "#BA7517",
    emoji: "🎉",
    cap: 5,
    subcategories: [
      { id: "dining", label: "Dining out / restaurant", emoji: "🍽️" },
      { id: "coffee", label: "Tea / coffee / chai", emoji: "☕" },
      { id: "snacks", label: "Snacks / outside food", emoji: "🍿" },
      { id: "movies", label: "Movies / OTT", emoji: "🎬" },
      { id: "entertainment", label: "Entertainment", emoji: "🎮" },
      { id: "shopping", label: "Clothes / shoes", emoji: "👗" },
      { id: "electronics", label: "Electronics / gadgets", emoji: "📱" },
      { id: "beauty", label: "Salon / grooming", emoji: "💅" },
      { id: "gym", label: "Gym / fitness", emoji: "🏋️" },
      { id: "travel_leisure", label: "Travel / holiday", emoji: "✈️" },
      { id: "gifts", label: "Gifts", emoji: "🎁" },
      { id: "subscriptions", label: "Subscriptions (Spotify etc)", emoji: "🎵" },
      { id: "online_shopping", label: "Amazon / Flipkart shopping", emoji: "📦" },
    ],
  },
  habits: {
    label: "Habits",
    color: "#E24B4A",
    emoji: "⚠️",
    cap: 0,
    subcategories: [
      { id: "cigarettes", label: "Cigarettes / tobacco", emoji: "🚬" },
      { id: "alcohol", label: "Alcohol / drinks", emoji: "🍺" },
      { id: "gutka", label: "Gutka / pan masala", emoji: "🌿" },
      { id: "gambling", label: "Gambling / lottery", emoji: "🎲" },
      { id: "paan", label: "Paan / supari", emoji: "🌿" },
    ],
  },
  loans: {
    label: "Loans & Credit",
    color: "#5F5E5A",
    emoji: "💳",
    cap: 40,
    subcategories: [
      { id: "home_loan_emi", label: "Home loan EMI", emoji: "🏠" },
      { id: "car_loan_emi", label: "Car loan EMI", emoji: "🚗" },
      { id: "personal_loan", label: "Personal loan EMI", emoji: "💰" },
      { id: "credit_card", label: "Credit card payment", emoji: "💳" },
      { id: "education_loan", label: "Education loan EMI", emoji: "🎓" },
      { id: "bike_loan", label: "Bike loan EMI", emoji: "🏍️" },
      { id: "bnpl", label: "Buy now pay later (EMI)", emoji: "📱" },
      { id: "other_loan", label: "Other loan", emoji: "💸" },
    ],
  },
  investment: {
    label: "Investments",
    color: "#1D9E75",
    emoji: "📈",
    cap: 20,
    subcategories: [
      { id: "sip", label: "SIP / Mutual fund", emoji: "📈" },
      { id: "ppf", label: "PPF", emoji: "🏛️" },
      { id: "epf", label: "EPF / PF", emoji: "🏛️" },
      { id: "nps", label: "NPS", emoji: "🏖️" },
      { id: "stocks", label: "Stocks / equity", emoji: "📊" },
      { id: "fd", label: "Fixed deposit", emoji: "🏦" },
      { id: "gold", label: "Gold / SGB", emoji: "🥇" },
      { id: "insurance_premium", label: "Insurance premium", emoji: "🛡️" },
      { id: "rd", label: "Recurring deposit", emoji: "📅" },
      { id: "crypto", label: "Crypto", emoji: "₿" },
    ],
  },
  income: {
    label: "Income",
    color: "#1D9E75",
    emoji: "💰",
    cap: 0,
    subcategories: [
      { id: "salary", label: "Salary", emoji: "💼" },
      { id: "freelance", label: "Freelance income", emoji: "💻" },
      { id: "rental", label: "Rental income", emoji: "🏢" },
      { id: "dividend", label: "Dividend / interest", emoji: "📊" },
      { id: "bonus", label: "Bonus", emoji: "🎉" },
      { id: "other_income", label: "Other income", emoji: "💸" },
    ],
  },
} as const;

export type BucketType = keyof typeof TRACKER_CATEGORIES;
